[build]
command = "python -m pip install -r requirements.txt && python -m pip install jupyterlite && python -m jupyterlite build --output-dir=./repl"
publish = "repl"

[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "ALLOWALL"
  Access-Control-Allow-Origin = "*"
